# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
    - jk-devel

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: |
      pip install --upgrade cython
      pip install --upgrade numpy
      pip install --upgrade scipy
    displayName: 'Install/upgrade cython, numpy, scipy'
  - script: |
      pip install -r requirements.txt
      pip install ipywidgets
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pip install .
      pytest -v --pyargs scqubits
      export OMP_NUM_THREADS=2
      export OPENBLAS_NUM_THREADS=2
      export MKL_NUM_THREADS=2
      export VECLIB_MAXIMUM_THREADS=2
      export NUMEXPR_NUM_THREADS=2
      pytest -v --pyargs scqubits --num_cpus=4
    displayName: 'Install scqubits and run pytest'
- job: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: |
      pip install --upgrade cython
      pip install --upgrade numpy
      pip install --upgrade scipy
    displayName: 'Install/upgrade cython, numpy, scipy'
  - script: |
      pip install -r requirements.txt
      pip install ipywidgets
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pip install .
      pytest -v --pyargs scqubits
      set OMP_NUM_THREADS=2
      set OPENBLAS_NUM_THREADS=2
      set MKL_NUM_THREADS=2
      set VECLIB_MAXIMUM_THREADS=2
      set NUMEXPR_NUM_THREADS=2
      pytest -v --pyargs scqubits --num_cpus=4
    displayName: 'Install scqubits and run pytest'
- job: macOS
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: |
      pip install --upgrade cython
      pip install --upgrade numpy
      pip install --upgrade scipy
    displayName: 'Install/upgrade cython, numpy, scipy'
  - script: |
      pip install -r requirements.txt
      pip install ipywidgets
    displayName: 'Install dependencies'
  - script: |
      pip install pytest pytest-azurepipelines
      pip install .
      pytest -v --pyargs scqubits
      export OMP_NUM_THREADS=2
      export OPENBLAS_NUM_THREADS=2
      export MKL_NUM_THREADS=2
      export VECLIB_MAXIMUM_THREADS=2
      export NUMEXPR_NUM_THREADS=2
      pytest -v --pyargs scqubits --num_cpus=4
    displayName: 'Install scqubits and run pytest'
